# Generated by Django 2.2.6 on 2020-03-18 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='name',
            field=models.CharField(default=datetime.datetime.now, max_length=100, verbose_name='User of the server'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ip',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Time of starting the server'),
            preserve_default=False,
        ),
    ]
